# Generated by Django 3.2.21 on 2023-09-18 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentGeneratorApp', '0003_auto_20230914_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='topic',
            new_name='blogIdea',
        ),
    ]
